### PR TITLE
Added cloneNode implemenation for DocumentFragment.

### PR DESCRIPTION
**Pull request by Indomian**
Added DocumentFragment.cloneNode implementation. Also increased utils/cloneNodeHelper code coverage and some refactoring done.

Egor Bolgov blade39@yandex.ru

### CODE REVIEW

**Comment by Indomian** [comment]
@christophehurpeau Hello, please, can you merge this? There is small change in code base. Also looks like coveralls is broken and not reporting status to github.

**Comment by christophehurpeau** [comment]
You can merge now, you are a contributor ! I don't have time for this project anymore. I'll check coveralls soon

**Comment by Indomian** [comment]
image No i can't :(

**Comment by christophehurpeau** [comment]
@Indomian if you rebase your branches, should work now. I switched to codecov

**Comment by Indomian** [comment]
@christophehurpeau Looks like i can't merge to master. As it says here: https://help.github.com/articles/about-protected-branches/ 

image

**Comment by christophehurpeau** [comment]
@Indomian you need to accept the invitation you received by email

**Comment by Indomian** [comment]
@christophehurpeau Done, but no changes. Looks like github misconfiguration?

**Comment by Indomian** [comment]
@christophehurpeau Hello again. Master brunch seems to be locked. I checked - i can merge to other branches, but not on master. I had this problem before - you need to unlock master branch so I will receive rights to merge to it. Now Master branch looks like this for me:
image

**Comment by christophehurpeau** [comment]
@Indomian Hello !

master is protected to prevent merging branches that do not pass tests

**Comment by christophehurpeau** [comment]
@Indomian Oh yes ! push was limited to administrators !

**Comment by Indomian** [comment]
Button enabled! Hurray!
image

**Pull request merged**
